name: pr

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar ambiente
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget unzip
          
          # Baixar e instalar o Android SDK manualmente
          ANDROID_SDK_ROOT=$HOME/android-sdk
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          cd $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d latest
          
          # Verificar se sdkmanager foi extraído corretamente
          ls -alh $ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          
          # Definir variáveis de ambiente
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          
          # Ajustar permissões de execução para sdkmanager
          sudo chmod +x $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager
          
          # Certificar que o sdkmanager está no PATH
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          
          # Testar se o sdkmanager está acessível
          sdkmanager --version || true
          sdkmanager --list || true

      - name: Iniciar Appium em background
        run: appium --log-level error &

      - name: Verificar dispositivos conectados
        run: adb devices

      - name: Criar e iniciar emulador Android
        run: |
          echo "Criando e iniciando emulador..."
          sdkmanager "system-images;android-30;default;x86_64"
          echo "no" | avdmanager create avd -n TestAVD -k "system-images;android-30;default;x86_64" --force
          nohup emulator -avd TestAVD -no-snapshot-load -no-audio -no-window &
          sleep 60  # Esperar o emulador carregar
          adb wait-for-device
          adb shell input keyevent 82  # Desbloquear tela

      - name: Executar testes automatizados
        run: mvn test

      - name: Upload de screenshots em caso de falha
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: $GITHUB_WORKSPACE/test-output
