name: pr

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar ambiente
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget unzip
          
          # Definir o diretório do SDK
          ANDROID_SDK_ROOT=$HOME/android-sdk
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          
          # Baixar o sdkmanager se não existir
          if [ ! -f "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" ]; then
            echo "Baixando sdkmanager..."
            wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
            unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools/latest/
            rm cmdline-tools.zip
          fi
          
          # Ajustar permissões
          sudo chmod -R +x $ANDROID_SDK_ROOT/cmdline-tools/latest/
          
          # Verificar a estrutura extraída
          echo "Conteúdo do diretório cmdline-tools/latest/bin:"
          ls -alh $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/
          
          # Definir variáveis de ambiente
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          
          # Verificar se sdkmanager e adb estão no PATH
          echo "Verificando sdkmanager e adb:"
          ls -alh $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/
          
          # Instalar as ferramentas necessárias para adb e emulator
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --update
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "emulator" "system-images;android-30;google_apis;x86_64"
          
          # Certificar que sdkmanager e adb estão no PATH
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          
          # Verificar se o sdkmanager está disponível
          sdkmanager --version || true
          adb version || true

      - name: Iniciar Appium em background
        run: appium --log-level error &

      - name: Verificar dispositivos conectados
        run: adb devices

      - name: Criar e iniciar emulador Android
        run: |
          echo "Criando e iniciando emulador..."
          sdkmanager "system-images;android-30;default;x86_64"
          echo "no" | avdmanager create avd -n TestAVD -k "system-images;android-30;default;x86_64" --force
          nohup emulator -avd TestAVD -no-snapshot-load -no-audio -no-window &
          sleep 60  # Esperar o emulador carregar
          adb wait-for-device
          adb shell input keyevent 82  # Desbloquear tela

      - name: Executar testes automatizados
        run: mvn test

      - name: Upload de screenshots em caso de falha
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: $GITHUB_WORKSPACE/test-output
