name: pr

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar ambiente
        run: |
          # Atualizar e instalar dependências
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget unzip

          # Definir o diretório do SDK
          ANDROID_SDK_ROOT=$HOME/android-sdk
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools

          # Baixar sdkmanager se não existir
          if [ ! -d "$ANDROID_SDK_ROOT/cmdline-tools/latest" ]; then
            echo "Baixando sdkmanager..."
            wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
            unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools/
            rm cmdline-tools.zip
          fi

          # Se o diretório latest não foi criado corretamente, criá-lo manualmente
          if [ ! -d "$ANDROID_SDK_ROOT/cmdline-tools/latest" ]; then
            echo "Criando diretório 'latest' manualmente..."
            mv $ANDROID_SDK_ROOT/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest
          fi

          # Adicionando cmdline-tools e platform-tools ao PATH
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          echo "Adicionando cmdline-tools e platform-tools ao PATH..."

          # Verificando sdkmanager e adb no PATH
          echo "Verificando sdkmanager..."
          which sdkmanager || echo "sdkmanager não encontrado"

          echo "Verificando adb..."
          which adb || echo "adb não encontrado"

          # Tentando instalar platform-tools explicitamente
          echo "Instalando platform-tools..."
          sdkmanager "platform-tools" || echo "Erro ao instalar platform-tools"

          # Verificando se o adb agora está disponível
          echo "Verificando adb após instalação..."
          which adb || echo "adb não encontrado após instalação"

          # Verificando o conteúdo do diretório platform-tools
          echo "Conteúdo do diretório platform-tools:"
          ls -la $ANDROID_SDK_ROOT/platform-tools || echo "Erro ao acessar o diretório platform-tools"

          # Tentando executar adb devices
          echo "Tentando adb devices..."
          adb devices || echo "adb devices falhou"

      - name: Iniciar Appium em background
        run: appium --log-level error &

      - name: Verificar dispositivos conectados
        run: adb devices

      - name: Criar e iniciar emulador Android
        run: |
          echo "Criando e iniciando emulador..."
          sdkmanager "system-images;android-30;default;x86_64"
          echo "no" | avdmanager create avd -n TestAVD -k "system-images;android-30;default;x86_64" --force
          nohup emulator -avd TestAVD -no-snapshot-load -no-audio -no-window &
          sleep 60  # Esperar o emulador carregar
          adb wait-for-device
          adb shell input keyevent 82  # Desbloquear tela

      - name: Executar testes automatizados
        run: mvn test

      - name: Upload de screenshots em caso de falha
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: $GITHUB_WORKSPACE/test-output
