name: pr

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar ambiente
        run: |
          # Atualizar e instalar dependência
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget unzip

          # Definir o diretório do SDK
          ANDROID_SDK_ROOT=$HOME/android-sdk
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          
          # Baixar sdkmanager se não existir
          if [ ! -d "$ANDROID_SDK_ROOT/cmdline-tools/latest" ]; then
            echo "Baixando sdkmanager..."
            wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
            unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools/
            rm cmdline-tools.zip
          fi
          
          # Criando o diretório latest, se necessário
          if [ ! -d "$ANDROID_SDK_ROOT/cmdline-tools/latest" ]; then
            echo "Criando diretório 'latest' manualmente..."
            mv $ANDROID_SDK_ROOT/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest
          fi
          
          # Adicionando sdkmanager, platform-tools e emulator ao PATH
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$PATH
          echo "Adicionando sdkmanager, platform-tools e emulator ao PATH..."
          echo "PATH: $PATH"

          # Verificando sdkmanager
          which sdkmanager || echo "sdkmanager não encontrado"
          which adb || echo "adb não encontrado"
          which emulator || echo "emulator não encontrado"

          # Aceitar licenças
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

          # Baixar platform-tools e emulador
          echo "Baixando platform-tools e emulador..."
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "emulator"

          # Verificando conteúdo do diretório platform-tools
          echo "Conteúdo do diretório platform-tools:"
          ls -la $ANDROID_SDK_ROOT/platform-tools || echo "Erro ao acessar o diretório platform-tools"
          
          # Tentando rodar adb devices
          echo "Tentando adb devices..."
          adb devices || echo "adb devices falhou"

      - name: Criar e iniciar emulador Android
        run: |
          echo "Criando e iniciando emulador..."
          
          # Baixar imagem do sistema Android
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "system-images;android-30;default;x86_64"

          # Criar AVD se não existir
          if [ ! -f "$HOME/.android/avd/TestAVD.ini" ]; then
            echo "Criando o AVD 'TestAVD'..."
            echo "no" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager create avd -n TestAVD -k "system-images;android-30;default;x86_64" --force
          else
            echo "AVD 'TestAVD' já existe!"
          fi

          # Listar AVDs disponíveis
          echo "Listando AVDs disponíveis..."
          $ANDROID_SDK_ROOT/emulator/emulator -list-avds

          # Iniciar o emulador
          nohup $ANDROID_SDK_ROOT/emulator/emulator -avd TestAVD -no-snapshot-load -no-audio -no-window &
          
          # Esperar o emulador carregar
          echo "Aguardando o emulador iniciar..."
          adb wait-for-device
          adb shell input keyevent 82  # Desbloquear tela

      - name: Executar testes automatizados
        run: mvn test

      - name: Upload de screenshots em caso de falha
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: $GITHUB_WORKSPACE/test-output