on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Instalar Android SDK e ferramentas
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O android-sdk.zip
          sudo mkdir -p /usr/local/android-sdk/cmdline-tools
          sudo unzip android-sdk.zip -d /usr/local/android-sdk/cmdline-tools
          sudo mv /usr/local/android-sdk/cmdline-tools/cmdline-tools /usr/local/android-sdk/cmdline-tools/latest
          export ANDROID_HOME=/usr/local/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30"

      - name: Compilar o projeto
        run: mvn clean compile

      - name: Iniciar API (se necessário)
        run: |
          nohup mvn spring-boot:run & 
          sleep 10  # Ajuste conforme o tempo de subida da API

      - name: Executar testes
        run: mvn test
