name: pr

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar ambiente
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk android-sdk
          echo "Configurando variáveis de ambiente..."
          echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "$ANDROID_HOME/tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH
          sdkmanager --list
          npm install -g appium

      - name: Iniciar Appium em background
        run: appium &

      - name: Verificar dispositivos conectados
        run: adb devices

      - name: Configurar permissões para SDK Android
        run: |
          sudo chmod -R 777 /usr/local/lib/android
          sudo chmod -R 777 $ANDROID_HOME

      - name: Iniciar emulador Android
        run: |
          echo "Iniciando emulador..."
          nohup emulator -avd NomeDoEmulador -no-snapshot-load -no-audio -no-window &  
          adb wait-for-device
          adb shell input keyevent 82  # Desbloquear emulador

      - name: Executar testes automatizados
        run: mvn test

      - name: Upload de screenshots em caso de falha
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: C:\PROJETOSQA\testesE2Eappium\test-output