name: pr

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar ambiente
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk android-sdk
          echo "Configurando variáveis de ambiente..."
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "$ANDROID_HOME/tools/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          export ANDROID_HOME=/usr/local/lib/android/sdk
          export PATH=$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH
          sdkmanager --list
          npm install -g appium

      - name: Iniciar Appium em background
        run: appium --log-level error &

      - name: Verificar dispositivos conectados
        run: adb devices

      - name: Criar e iniciar emulador Android
        run: |
          echo "Criando e iniciando emulador..."
          sdkmanager "system-images;android-30;default;x86_64"
          echo "no" | avdmanager create avd -n TestAVD -k "system-images;android-30;default;x86_64" --force
          nohup emulator -avd TestAVD -no-snapshot-load -no-audio -no-window &
          sleep 60  # Esperar o emulador carregar
          adb wait-for-device
          adb shell input keyevent 82  # Desbloquear tela

      - name: Executar testes automatizados
        run: mvn test

      - name: Upload de screenshots em caso de falha
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: $GITHUB_WORKSPACE/test-output
